kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-manager
  namespace: application1-dev
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]